jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
    - continue-on-error: true
      run: ./gradlew build -Pmod_version="$(git describe --always --tags | cut -c2-)"
        --stacktrace --no-daemon
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: clientcommands-snapshot
        path: build/libs/
name: Check and Release Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
